### ISSUE TITLE
Feature SQLite Support

### ISSUE THREAD

**Issue by tracker1** [brunohbrito/JPProject.IdentityServer4.AdminUI#49]
Would be nice to have SQLite support.  It'd be a great option for small or test/qa environments.  For docker-compose would only need to use a named volume instead of the jpdatabase container.

docker-compose.sqlite.yml
```
volumes:
  data-store:
    driver: local
services:
  jpproject:
    ...
    volumes:
      - data-store:/var/lib/identityserver/data
    environment:
      ...
      CUSTOMCONNSTR_SSOConnection: "Filename=/var/lib/identityserver/data/identityserver.sqlite"
...
```
